version: "3.7"

services:
    database:
        container_name: personal-mariadb
        build:
            context: ./database
        environment:
            - MYSQL_DATABASE=${DATABASE_NAME}
            - MYSQL_USER=${DATABASE_USER}
            - MYSQL_PASSWORD=${DATABASE_PASSWORD}
            - MYSQL_ROOT_PASSWORD=${DATABASE_ROOT_PASSWORD}
        volumes:
            - ./database/init.sql:/docker-entrypoint-initdb.d/init.sql
            - ./database/data:/var/lib/mysql
        networks:
            - database
    php:
        container_name: personnal-php-fpm
        build:
            context: ./php-fpm
        depends_on:
            - database
        volumes:
            - ../sources:/var/www
        networks:
            - database
            - php
    nginx:
        container_name: personnal-nginx
        build:
            context: ./nginx
        volumes:
            - ../sources:/var/www
            - ./nginx/nginx.conf:/etc/nginx/nginx.conf
            - ./nginx/sites/:/etc/nginx/sites-available
            - ./nginx/conf.d/:/etc/nginx/conf.d
            - ./logs:/var/log
        depends_on:
            - php
        networks:
            - php
        ports:
            - ${NGINX_PORT}:80
            - ${NGINX_HTTPS}:443
networks:
    database:
    php: